name: Build
on:
  pull_request:
  push:
    branches:
      - l7

jobs:
  be-build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Deps
        run: cd backend && npm i

      - name: Build
        run: cd backend && npm run build

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: backend/build/

  be-lint:
    needs: [be-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i

      - name: Lint the code
        run: cd backend && npm run lint

  be-test:
    needs: [be-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i

      - name: Run Unit Tests
        run: cd backend && npm t

  be-security-audit:
    needs: [be-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check for security issue
        run: cd backend && npm audit --production --audit-level=medium

  be-static-analysis:
    needs: [be-build,be-lint,be-test,be-security-audit]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v1

      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v1
      #   with:
      #     languages: javascript

      # - name: Setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x

      # - name: Install Deps
      #   run: cd backend && npm i

      # - name: Build
      #   run: cd backend && npm run build

      # - name: Perform Analysis
      #   uses: github/codeql-action/analyze@v1

  fe-build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Deps
        run: cd frontend && npm i

      - name: Build
        run: |
          export REACT_APP_API_HOST=__BACKEND_URL_PLACEHOLDER__
          cd frontend && npm run build

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: frontend/build

  fe-security-audit:
    needs: [fe-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check for security issue
        run: cd frontend && npm audit --production --audit-level=critical
  
  fe-static-analysis:
    needs: [fe-security-audit]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v1

      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v1
      #   with:
      #     languages: javascript

      # - name: Setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x

      # - name: Cache Node Modules
      #   id: cache
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: node-modules-cache
          
      # - name: Install Deps
      #   run: cd frontend && npm i

      # - name: Build
      #   run: cd frontend && npm run build

      # - name: Perform Analysis
      #   uses: github/codeql-action/analyze@v1  

  trigger-deploy:
    #if: github.ref == 'refs/heads/main'
    needs: [be-static-analysis, fe-static-analysis]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy Candidate

  