name: Cleanup Infrastructure
on:  
   workflow_dispatch:
    inputs:
      ref:
        required: true

jobs:
  destroy_infrastructure:
    runs-on: ubuntu-latest
    steps:      
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.event.inputs.ref }}          
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Destroy Frontend
        uses: dflook/terraform-destroy@v1
        with:
          path: util/terraform/frontend
          workspace: anyhasher-frontend-${{ github.event.inputs.ref }}
          
      - name: Destroy Backend
        uses: dflook/terraform-destroy@v1
        with:
          path: util/terraform/backend
          workspace: anyhasher-backend-${{ github.event.inputs.ref }}

      - run: echo Need to hook up slack here!