name: Destroy
on:  
  workflow_dispatch:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.2.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Destroy Backend Infrastructure
        run: |
          cd util/terraform/backend
          terraform init -var instance_name=null
          terraform destroy -auto-approve
    
      - name: Destroy Frontend Infrastructure
        run: | 
          cd util/terraform/frontend
          terraform init -var bucket_name=null
          terraform destroy -auto-approve