name: Continuous Integrations
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1 #brings the code down to the computer that executes the pipeline
      - run: cd backend && npm i # install all the packages that we have in this backend
      - run: cd backend && nmp build # to build the code
      