name: Continuous Integrations
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - run: cd backend
      - run: npm i # install all the packages that we have in this backend
      - run: nmp build # to build the code
      