name: Promote
run-name: "🤩 CD: Promote Green to Blue (And Decommission Previous Blue)"
on:  
  workflow_dispatch:
    inputs:
      ref:
        required: true
      frontend_url:
        required: true
      
jobs:
  old_blue_ref:
    name: Get Previous Blue Ref
    runs-on: ubuntu-latest
    steps:
      - name: Get Previous Blue Version
        run: echo "old_blue_ref=$(git tag --list --sort=-version:refname "blue*" | head -n 1)" >> $GITHUB_ENV

  promote:
    name: 🚀 Promote Green to Blue     
    needs: [old_blue_ref]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Change CloudFront "Router"
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: promote.yml
          directory: ./util/ansible
          options: |
            --verbose
            --extra-vars "distro_id='${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}' origin_domain='${{ github.event.inputs.frontend_url }}'"
  
      - name: Tag Green as New Blue
        if: success()         
        run: |
          git tag "blue/${{ github.event.inputs.ref }}"
          git push origin "blue/${{ github.event.inputs.ref }}"     

  cleanup_failing_green:
    name: 🍋 Clean up Failing Green
    needs: [promote]
    if: failure()         
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ github.event.inputs.ref }}" }'

  cleanup_old_blue:
    name: Clean up Previous Blue
    needs: [promote]
    if: success()      
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ env.old_blue_ref }}" }'