name: Promote
on:  
  workflow_dispatch:
    inputs:
      ref:
        required: true
      frontend_url:
        required: true
      
jobs:
  promote_green_to_blue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Change CloudFront "Router"
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: promote.yml
          directory: ./util/ansible
          options: |
            --verbose
            --extra-vars "distro_id='${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}' origin_domain='${{ github.event.inputs.frontend_url }}'"
  
      - name: Get Previous Blue Version
        run: echo "old_blue_ref=$(git describe --match "blue" --abbrev=4 HEAD^)" >> $GITHUB_ENV

      - name: Tag Green as New Blue
        if: success()         
        run: |
          git tag "blue/${{ github.sha }}"
          git push origin "blue/${{ github.sha }}"     

      # - name: Trigger Cleanup for Old Blue
      #   if: success()         
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: Cleanup
      #     inputs: '{ "ref": "${{ env.old_blue_ref }}" }' 
        
      - name: Cleanup Green Infrastructure After Failure
        if: failure()         
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ github.sha }}" }' 
          
  trigger-cleanup:
    needs: [promote_green_to_blue]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ env.old_blue_ref }}" }'