name: Promote
run-name: "🤩 CD: Promote Green to Blue (And Decommission Previous Blue)"
on:  
  workflow_dispatch:
    inputs:
      ref:
        required: true
      frontend_url:
        required: true
      
jobs:
  
  promote:
    name: 🚀 Promote Green to Blue     
    runs-on: ubuntu-latest
    container: python:3.7
    outputs:
      previous_tag: ${{ steps.previous.outputs.tag }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          depth: 0
      
      - name: Setting Safe Directory # work-around for gitconfig in container (https://github.com/actions/checkout/issues/1169)
        run: git config --system --add safe.directory ./
        
      - name: Find Previous Blue Version
        id: previous
        uses: jimschubert/query-tag-action@v1
        with:
          skip-unshallow: true
          include: 'blue/*'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Change CloudFront "Router"
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: promote.yml
          directory: ./util/ansible
          options: |
            --verbose
            --extra-vars "distro_id='${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}' origin_domain='${{ github.event.inputs.frontend_url }}'"
  
      - name: Tag Green as New Blue
        if: success()         
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "blue/${{ github.event.inputs.ref }}"

  cleanup_failing_green:
    name: ❌ Clean up Failing Green
    needs: [promote]
    if: failure()         
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ github.event.inputs.ref }}" }'

  cleanup_old_blue:
    name: ❌ Clean up Previous Blue
    needs: [promote]
    if: success()  
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Old Blue
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.promote.outputs.previous_tag }}

      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ github.sha }}" }'
