name: Verify
on:
  workflow_dispatch:
    inputs:
      backend_url:
        required: true
      frontend_url:
        required: true
      ref:
        required: true
        
jobs:
  verify-frontend:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Frontend Smoke Test
        run: |
          export TEST_URL=${{ github.event.inputs.frontend_url }}
          cd frontent/e2e
          npm install
          npm run frontend-smoke  

      - name: Cleanup On Failure
        if: failure()     
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ github.event.inputs.ref }}" }'
    
  verify-backend:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Backend Smoke Test
        run: |
          export BACKEND_URL=${{ github.event.inputs.backend_url }}
          cd backend/e2e
          chmod +x backend-smoke.sh
          ./backend-smoke.sh
      
      - name: Cleanup On Failure
        if: failure()             
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ github.event.inputs.ref }}" }'
        
  trigger-promotion:
    needs: [verify-backend,verify-frontend]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Promote
          inputs: '{ "ref": "${{ github.events.inputs.ref }}" }'
