name: Verify
on:
  workflow_dispatch:
    inputs:
      backend_url:
        required: true
      frontend_url:
        required: true
      ref:
        required: true
        
jobs:
  frontend:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Frontend Smoke Test
        run: |
          export TEST_URL=${{ github.event.inputs.frontend_url }}
          cd frontend/e2e
          npm install
          npm run smoke  
    
  backend:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Backend Smoke Test
        run: |
          export BACKEND_URL=${{ github.event.inputs.backend_url }}
          cd backend/e2e
          chmod +x backend-smoke.sh
          ./backend-smoke.sh
          
  trigger-cleanup:
    if: needs.testsjob.result !== 'success'
    needs: [backend,frontend]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Cleanup On Failure
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Cleanup
          inputs: '{ "ref": "${{ github.event.inputs.ref }}" }'
              
  trigger-promotion:
    if: needs.testsjob.result == 'success'
    needs: [backend,frontend]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Promote
          inputs: '{ "ref": "${{ github.events.inputs.ref }}" }'
