name: Verify
on:
  workflow_dispatch:

jobs:
  verify-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Frontend Smoke Test
        run: |
          export TEST_URL=${{ needs.provision_infrastructure.outputs.frontend_url }}
          cd e2e
          npm install
          npm run frontend-smoke  

      - name: Cleanup On Failure
        if: failure()         
        run: |
          git tag "cleanup/${{ github.sha }}"
          git push origin "cleanup/${{ github.sha }}" 
    
  verify-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Backend Smoke Test
        run: |
          export BACKEND_URL=${{ needs.provision_infrastructure.outputs.backend_url }}
          cd e2e
          chmod +x backend-smoke.sh
          ./backend-smoke.sh
      
      - name: Cleanup On Failure
        if: failure()         
        run: |
          git tag "cleanup/${{ github.sha }}"
          git push origin "cleanup/${{ github.sha }}" 
    
  trigger-promotion:
    needs: [verify-backend,verify-frontend]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Promote